name: Format code with Ormolu
author: Nikita Volkov
inputs:
  dirs:
    description: Space-separated list of dirs to format. If not specified, all .hs files will be formatted (excluding dist-newstyle and .git directories)
    required: false
    default: ''
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/ormolu.github-action:2233f0e2087a3e7c10f84ddf96aa2fabc7ef8a17
