on:
  push:
    branches:
      - major
      - minor
      - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: docker
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.12.3
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://ghcr.io/${{ github.repository }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - id: update-image-ref
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docker image ref
          file_pattern: action.yml

      - id: tag
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: major,minor,patch
          github_token: ${{ github.token }}
          default_bump: ${{ github.ref_name }}
          commit_sha: ${{ steps.update-image-ref.outputs.commit_hash }}

      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ github.token }}
          commit: ${{ github.ref_name }}
          tag: ${{ steps.tag.outputs.new_tag }}

      - name: Merge to master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: master
          github_token: ${{ github.token }}
